<?php

return [
    'project' => [
        'name' => 'Leede Fusion',
        'owner' => 'Intizar Wahla',
        'phone' => '03066978156',
        'email' => 'leede@gmail.com',
        'location' => 'Karachi, Sindh, Pakistan',
        'hours' => '9:00 AM – 9:00 PM (7 Days a Week)',
        'whatsapp' => '03066978156',
        'whatsapp_link' => 'https://wa.me/923066978156',
        'whatsapp_international' => '923066978156',
    ],

    'hero_slides' => [
        [
            'id' => 1,
            'badge' => "MODERN WOMEN'S & BESPOKE DESIGN HOUSE",
            'title' => 'YOUR IDEA. OUR CRAFT.',
            'description' => "Women's & Men's custom designs, bespoke stitching, bespoke Abayas and thoughtful fitting — created around you.",
            'primary_btn_text' => 'START YOUR DESIGN',
            'primary_btn_action' => 'custom-design',
            'secondary_btn_text' => 'EXPLORE COLLECTION',
            'secondary_btn_url' => '/collections',
            'image' => '/hero-fashion.webp',
            'theme' => 'light',
        ],
        [
            'id' => 2,
            'badge' => 'SIGNATURE READY-TO-WEAR DROPS',
            'title' => 'ELEGANCE IN EVERY THREAD.',
            'description' => 'Discover our premium ready-to-wear luxury lawn, embellished pret, and seasonal designer collections.',
            'primary_btn_text' => 'EXPLORE COLLECTION',
            'primary_btn_url' => '/collections',
            'secondary_btn_text' => 'START YOUR DESIGN',
            'secondary_btn_action' => 'custom-design',
            'image' => '/1.jpg',
            'theme' => 'dark',
        ],
        [
            'id' => 3,
            'badge' => 'OEM & BESPOKE APPAREL MANUFACTURING',
            'title' => 'FROM SKETCH TO PERFECTION.',
            'description' => 'Bespoke tailoring, boutique manufacturing, and bulk custom order fulfillment for brands and independent designers.',
            'primary_btn_text' => 'START YOUR DESIGN',
            'primary_btn_action' => 'custom-design',
            'secondary_btn_text' => 'OUR CRAFTSMANSHIP',
            'secondary_btn_url' => '/story',
            'image' => '/2.jpg',
            'theme' => 'dark',
        ],
        [
            'id' => 4,
            'badge' => 'HERITAGE & ARTISANAL CRAFT',
            'title' => 'QUALITY YOU CAN TRUST.',
            'description' => 'Serving Karachi and worldwide with finest fabrics, master cutting, and immaculate hand-stitched finishes.',
            'primary_btn_text' => 'EXPLORE COLLECTION',
            'primary_btn_url' => '/collections',
            'secondary_btn_text' => 'GET IN TOUCH',
            'secondary_btn_action' => 'custom-design',
            'image' => '/4.jpg',
            'theme' => 'dark',
        ],
    ],

    'why_shop' => [
        [
            'title' => 'PREMIUM QUALITY',
            'description' => 'We source only the finest fabrics and branded suits to ensure our customers get the best quality in Karachi.',
            'icon' => 'quality',
        ],
        [
            'title' => 'WHATSAPP ENQUIRY',
            'description' => 'Easy and direct communication. Simply send us a message to enquire about any product or price.',
            'icon' => 'whatsapp',
        ],
        [
            'title' => 'NATIONWIDE DELIVERY',
            'description' => 'Based in Karachi, but delivering everywhere via reliable third-party couriers like Bykea.',
            'icon' => 'delivery',
        ],
    ],

    'blog_posts' => [
        [
            'id' => 1,
            'title' => 'The Art of Luxury Lawn: Crafting Elegance for Every Season',
            'slug' => 'art-of-luxury-lawn',
            'category' => 'Fabric & Craftsmanship',
            'date' => 'September 18, 2026',
            'read_time' => '4 min read',
            'image' => '/1.jpg',
            'excerpt' => 'Discover the meticulous craftsmanship behind high-thread-count Egyptian cotton, breathable weaves, and timeless floral and geometric motifs.',
            'content' => "Lawn fabric has long been the cornerstone of Pakistani haute couture. At Leedee Fusion, each collection begins with hand-selected long-staple cotton fibres, spun to optimum tensile strength. This ensures our fabrics remain whisper-light during peak summer days while retaining their structural drape. Paired with Swiss voile dupattas and pure silk accents, our signature lawn suits celebrate heritage embroidery techniques reimagined for the modern silhouette.",
        ],
        [
            'id' => 2,
            'title' => 'Men\'s Kurta Styling Guide: From Daily Elegance to Festive Evenings',
            'slug' => 'mens-kurta-styling-guide',
            'category' => 'Men\'s Couture',
            'date' => 'September 14, 2026',
            'read_time' => '5 min read',
            'image' => '/4.jpg',
            'excerpt' => 'From Royal Oxford washes to textured wash-and-wear blends, learn how to select the right collar cuts, cuffs, and accessories for any occasion.',
            'content' => "The classic Kurta Shalwar remains the definitive expression of masculine refinement in South Asia. Whether opting for our Royal Oxford fabric with subtle lustre or breathable linen blends, the key lies in the precision of the cut. Pair a crisp band-collar kurta with traditional handcrafted Peshawari chappals for daytime elegance, or layer with a structured raw silk waistcoat for evening celebrations.",
        ],
        [
            'id' => 3,
            'title' => 'Timeless Monochrome: Balancing Minimalist Lines with Regal Accents',
            'slug' => 'timeless-monochrome-styling',
            'category' => 'Style Journal',
            'date' => 'September 08, 2026',
            'read_time' => '3 min read',
            'image' => '/2.jpg',
            'excerpt' => 'How subtle zari detailing, tonal block prints, and fluid hemlines can transform understated monochromatic palettes into runway-ready statements.',
            'content' => "While vibrant jewel tones have their place, nothing commands effortless grace quite like monochromatic tailoring. Our latest pret and unstitched collections feature nuanced contrasts: ivory threads on charcoal cambric, deep obsidian silks with matte silver borders, and tone-on-tone self-jacquards. Discover the balance between understated minimalism and royal heritage.",
        ],
    ],
];
